baseURL = "https://karlgrz.com/"
relativeURLs = true
title = "karlgrz"
languageCode = "en-us"
disqusShortname = "karlgrz"
MetaDataFormat = "toml"
theme = "hyde"
paginate = 5
googleAnalytics = "UA-40361995-1"
gravatarHash = "c89d7aaa0fd05ebbf6326e2da6c9552e"

[Menus]
  main = [
    {Name = "Github", URL = "https://github.com/karlgrz"},
    {Name = "Bitbucket", URL = "https://bitbucket.org/karlgrz"},
    {Name = "Twitter", URL = "https://twitter.com/karl_grz"},
    {Name = "YouTube", URL = "https://youtube.com/KarlGrzeszczak"}
]

[author]
  name = "karlgrz"

[permalinks]
  # Optional. Change the permalink format for the 'post' content type.
  # The format shown here is the same one Jekyll/Octopress uses by default.
  post = "/:slug"

[params]
  # If false display full article contents in blog index.
  # Otherwise show description and 'read on' link to individual blog post page.
  # Default (if omitted) is true.
  truncate = true

  # Used when a given page doesn't set its own.
  description = "symphonic code"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "sunburst"

  # Text for the top menu link, which goes the root URL for the site.
  # Default (if omitted) is "Blog".
  home = "Blog"

  # Other social-like sidebar links
  rss = false  # switch to true to enable RSS icon link
